---
version: '2'

services:

  lode:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
         LODE_EXTERNAL_URL: http://localhost:8080/lode
         WEBVOWL_EXTERNAL_URL: http://visualdataweb.de/webvowl/#iri=
    container_name: lode
    ports:
      - 8080:8080/tcp
